### ISSUE TITLE
Support for plugins downloaded from a different source

### ISSUE THREAD

**Issue by clarsonneur** [forj-oss/jplugins#30]
jplugins should support installing plugins from a different source so that it can check and update the plugin from that source.

ex: [Veracode jenkins plugins](https://help.veracode.com/reader/PgbNZUD7j8aY7iG~hQZWxQ/DhfpJ3OQzjGCQ3M9mTzfhg) 

This page explains how to download a version from their site ie:
https://tools.veracode.com/integrations/Jenkins/bin/veracode-jenkins-plugin.hpi

We can define it in the features.lst as follow:

```
plugin:veracode-jenkins-plugin::https://tools.veracode.com/integrations/Jenkins/bin/veracode-jenkins-plugin.hpi
```
But It could be incompatible with the way this lst file is already managed. To verify.

A better approach could be to use a features.yaml. This approach requires a little more development.
But that way we can configure jplugins features better.

```yaml
plugins:
  veracode-jenkins-plugin:
     source: https://tools.veracode.com/integrations/Jenkins/bin/veracode-jenkins-plugin.hpi
     source-type: download # default to `updates-repo`
     version: # default to latest
```
